### ISSUE TITLE
The link of 'Yolo weights and .cfg files ' and 'Pointing Gesture classifier' are same?

### ISSUE THREAD

**Issue by Billccx** [islboun/3D_Pointing_Estimation#1]
Hello! 
I noticed that the link to download 'Yolo weights and .cfg files' is identical with the link to download 'Pointing Gesture classifier'. 
Both `https://cloud.boun.edu.tr/public.php?service=files&t=057b9daac0d636ca75da0a64345280e5.` 
Is that right? 
I am looking forward to your reply and thanks in advance.

**Comment by mirhanu** [comment]
Yes, they are the same. You can find the related files in the link.
